# Generated by Django 2.2 on 2019-06-20 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='Email address')),
                ('firstName', models.CharField(max_length=100, verbose_name='First Name')),
                ('lastName', models.CharField(max_length=100, verbose_name='Last Name')),
                ('profilePicture', models.ImageField(default='Accounts/Users/ProfilePictures/defaultAvatar.png', upload_to='Accounts/Users/ProfilePictures', verbose_name='Profile Picture')),
                ('mobileNumber', models.CharField(max_length=20, null=True, verbose_name='Mobile number')),
                ('permanentAddress', models.TextField(null=True, verbose_name='Permanent Address')),
                ('city', models.CharField(max_length=30, null=True, verbose_name='City')),
                ('code', models.CharField(max_length=15, null=True, verbose_name='Zip/Pin Code')),
                ('country', models.CharField(max_length=30, null=True, verbose_name='Country')),
                ('dateJoined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Joined')),
                ('verified', models.BooleanField(default=False, verbose_name='Verified ')),
                ('active', models.BooleanField(default=True)),
                ('consumerUser', models.BooleanField(default=False)),
                ('merchantUser', models.BooleanField(default=False)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.IntegerField(default=0, verbose_name='OTP Generated')),
                ('dateTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date And Time Generated')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OTP',
                'verbose_name_plural': 'OTPs',
            },
        ),
    ]
