# Generated by Django 2.2 on 2019-06-20 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('categoryId', models.AutoField(primary_key=True, serialize=False, verbose_name='Category Id')),
                ('categoryName', models.CharField(max_length=30, verbose_name='Category Name')),
                ('categoryImage', models.ImageField(upload_to='Products/Categories', verbose_name='Category Image')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('productId', models.AutoField(primary_key=True, serialize=False, verbose_name='Product ID')),
                ('productName', models.CharField(max_length=30, verbose_name='Product Name')),
                ('productImage', models.ImageField(upload_to='Products/ProductImages', verbose_name='Product Image')),
                ('productStock', models.IntegerField(default=0, verbose_name='Product Stock')),
                ('productPrice', models.BigIntegerField(default=0, verbose_name='Product Price')),
                ('productSeller', models.CharField(max_length=50, verbose_name='Product Seller')),
                ('productSpecifications', models.TextField(verbose_name='Product Specifications')),
                ('productDescriptions', models.TextField(verbose_name='Product Descriptions')),
                ('countryOfManufacture', models.CharField(max_length=50, verbose_name='Country Of Manufacture')),
                ('warrantyPeriod', models.IntegerField(default=0, verbose_name='Warranty Period')),
                ('noOfPurchases', models.IntegerField(default=0, verbose_name='No of Purchases')),
                ('productCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Categories')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
